### ISSUE TITLE
Wrong demonstration

### ISSUE THREAD

**Issue by DamonJason** [voilet/smartdns#1]
You used the wrong command in the documentation as a demonstration, which is dangerous behavior. We hope to correct it to avoid misleading everyone 

"zone format in redis db" - "zones" - "KEYS *"

https://redis.io/docs/latest/commands/keys/

**Comment by voilet** [comment]
fix keys example*
Thanks

**Comment by voilet** [comment]
fix keys example*
Thanks

**Comment by voilet** [comment]
fix keys example*
Thanks

**Comment by voilet** [comment]
fix keys example*
Thanks
